create table usuario (id  serial not null, login varchar(20) not null, senha varchar(20) not null, nome varchar(50) not null, casaid int4, primary key (id), constraint UIDX_USUARIO_LOGIN unique (login));
create table eventobanda (id  serial not null, eventoid int4 not null, bandaid int4 not null, primary key (id), constraint UIDX_EVENTOBANDA_EVENTO_BANDA unique (eventoid, bandaid));
create table evento (id  serial not null, dataHora date not null, valor float8 not null, casaid int4, primary key (id));
create table musicobanda (id  serial not null, musicoid int4 not null, bandaid int4 not null, funcao varchar(30) not null, primary key (id), constraint UIDX_MUSICOBANDA_MUSICO_BANDA unique (musicoid, bandaid));
create table contatomusico (id  serial not null, musicoid int4 not null, contatoid int4 not null, primary key (id), constraint UIDX_CONTATOMUSICO_CONTATO_MUSICO unique (contatoid, musicoid));
create table musico (id  serial not null, nome varchar(100) not null, primary key (id), constraint UIDX_MUSICO_NOME unique (nome));
create table contatobanda (id  serial not null, bandaid int4 not null, contatoid int4 not null, primary key (id), constraint UIDX_CONTATOBANDA_BANDA_CONTATO unique (bandaid, contatoid));
create table banda (id  serial not null, nome varchar(50) not null, dataFormacao date, primary key (id), constraint UIDX_BANDA_NOME unique (nome));
create table contatocasa (id  serial not null, contatoid int4 not null, casaid int4, primary key (id), constraint UIDX_CONTATOCASA_CONTATO unique (contatoid));
create table contato (id  serial not null, telefone varchar(10), fax varchar(10), email varchar(100), site varchar(100), facebook varchar(100), twitter varchar(30), primary key (id));
create table endereco (id  serial not null, cidadeid int4 not null, bairro varchar(30), cep varchar(8), logradouro varchar(100), complemento varchar(255), numero varchar(10), primary key (id));
create table cidade (id  serial not null, nome varchar(50) not null, ufid int4 not null, primary key (id), constraint UIDX_CIDADE_NOME_UF unique (nome, ufid));
create table uf (id  serial not null, sigla varchar(2) not null, nome varchar(30) not null, primary key (id), constraint UIDX_UF_NOME unique (nome), constraint UIDX_UF_SIGLA unique (sigla));
create table casa (id  serial not null, nome varchar(80) not null, enderecoid int4 not null, matrizid int4, cnpj int4 not null, responsavel varchar(100) not null, primary key (id), constraint UIDX_CASA_CNPJ unique (cnpj), constraint UIDX_CASA_NOME unique (nome), constraint UIDX_CASA_ENDERECO unique (enderecoid));
alter table eventobanda add constraint FK_EVENTOBANDA_BANDA foreign key (bandaid) references banda (id);
alter table eventobanda add constraint FK_EVENTOBANDA_EVENTO foreign key (eventoid) references evento (id);
alter table evento add constraint FK_EVENTO_CASA foreign key (casaid) references casa (id);
alter table usuario add constraint FK_USUARIO_CASA foreign key (casaid) references casa (id);
alter table contatomusico add constraint FK_CONTATOMUSICO_CONTATO foreign key (contatoid) references contato (id);
alter table contatomusico add constraint FK_CONTATOMUSICO_MUSICO foreign key (musicoid) references musico (id);
alter table musicobanda add constraint FK_MUSICOBANDA_BANDA foreign key (bandaid) references banda (id);
alter table musicobanda add constraint FK_MUSICOBANDA_MUSICO foreign key (musicoid) references musico (id);
alter table cidade add constraint FK_CIDADE_UF foreign key (ufid) references uf (id);
alter table endereco add constraint FK_ENDERECO_CIDADE foreign key (cidadeid) references cidade (id);
alter table casa add constraint FK_CASA_ENDERECO foreign key (enderecoid) references endereco (id);
alter table casa add constraint FK_CASA_CASA foreign key (matrizid) references casa (id);
alter table contatocasa add constraint FK_CONTATOCASA_CASA foreign key (casaid) references casa (id);
alter table contatocasa add constraint FK_CONTATOCASA_CONTATO foreign key (contatoid) references contato (id);
alter table contatobanda add constraint FK_CONTATOBANDA_CONTATO foreign key (contatoid) references contato (id);
alter table contatobanda add constraint FK_CONTATOBANDA_BANDA foreign key (bandaid) references banda (id);

