alter table eventobanda drop constraint FK_EVENTOBANDA_BANDA;
alter table eventobanda drop constraint FK_EVENTOBANDA_EVENTO;
alter table evento drop constraint FK_EVENTO_CASA;
alter table usuario drop constraint FK_USUARIO_CASA;
alter table contatomusico drop constraint FK_CONTATOMUSICO_CONTATO;
alter table contatomusico drop constraint FK_CONTATOMUSICO_MUSICO;
alter table musicobanda drop constraint FK_MUSICOBANDA_BANDA;
alter table musicobanda drop constraint FK_MUSICOBANDA_MUSICO;
alter table cidade drop constraint FK_CIDADE_UF;
alter table endereco drop constraint FK_ENDERECO_CIDADE;
alter table casa drop constraint FK_CASA_ENDERECO;
alter table casa drop constraint FK_CASA_CASA;
alter table contatocasa drop constraint FK_CONTATOCASA_CASA;
alter table contatocasa drop constraint FK_CONTATOCASA_CONTATO;
alter table contatobanda drop constraint FK_CONTATOBANDA_CONTATO;
alter table contatobanda drop constraint FK_CONTATOBANDA_BANDA;
drop table usuario cascade;
drop table eventobanda cascade;
drop table evento cascade;
drop table musicobanda cascade;
drop table contatomusico cascade;
drop table musico cascade;
drop table contatobanda cascade;
drop table banda cascade;
drop table contatocasa cascade;
drop table contato cascade;
drop table endereco cascade;
drop table cidade cascade;
drop table uf cascade;
drop table casa cascade;

